// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvsgkqcnivbmisbfegkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2c2drcWNuaXZibWlzYmZlZ2t2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwNzUyNzQsImV4cCI6MjA2MzY1MTI3NH0.9MLGnrFby62Zpjq5ORttAXG28Ie8-RPsni-G9-mpQpo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);